app/jaythree/urls.py
from django import views
from pos import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pos/', include('pos.urls')),
    path('', views.dashboard, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('stock', views.stock, name='stock'),
    path('products', views.products, name='products'),
    path('save_product', views.save_product, name='save_product'),
    path('delete_product/<str:product_id>', views.delete_product, name='delete_product'),
    path('update_product/<str:product_id>', views.update_product, name='update_product'),
    path('add_stock/<str:product_id>', views.add_stock, name='add_stock'),
    path('remove_stock/<str:product_id>', views.remove_stock, name='remove_stock'),
]

jaythree/urls.py
from django import views
from pos import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pos/', include('pos.urls')),
    path('', views.dashboard, name='dashboard'),
    path('accounts/login/', views.login, name='login')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('pos', views.pos, name='pos'),
    path('login', views.login, name='login'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.signup, name='signup'),
    path('account', views.account, name='account'),
    path('change_password', views.change_password, name='change_password'),
    path('update_product/<str:product_id>', views.update_product, name='update_product'),
    path('reports', views.reports, name='reports'),
    path('stock/<int:page>',views.stock,name='stock'),
    path('sales/<int:page>',views.sales,name='sales'),
    path('products/<int:page>',views.products,name='products'),
    path('remove_item/', views.remove_item, name='remove_item'),
    path('receipt/<int:sale_id>', views.receipt, name='receipt'),
    path('save_product', views.save_product, name='save_product'),
    path('receipt/<int:sale_id>', views.receipt, name='sale_receipt'),
    path('add_stock/<str:product_id>', views.add_stock, name='add_stock'),
    path('remove_stock/<str:product_id>', views.remove_stock, name='remove_stock'),
    path('delete_product/<str:product_id>', views.delete_product, name='delete_product'),
    path('update_product/<str:product_id>', views.update_product, name='update_product'),
]

app/pos/views.py
from django.shortcuts import redirect, render
from django.shortcuts import render, redirect
from pos.models import Product
from django.contrib import messages

def dashboard(request):
    context = {}
    return render(request, 'pos/user/dashboard.html', context)


def products(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }
    return render(request, 'pos/user/products.html', context)


def save_product(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }

    if request.method == "POST":
        name = request.POST['name']
        quantity = request.POST['quantity']
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        newproduct = Product.objects.create(name=name, quantity=quantity, unit_price=unit_price,
                                            description=description)

        newproduct.save()
        messages.success(request, "Product (" + name + ") Created Successfully. \n ")

        return redirect('pos:products')
    return render(request, 'pos/user/new_product.html', context)


def update_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product_id = product.product_id
        name = request.POST['name']
        quantity = product.quantity
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Product (" + name + ") Updated Successfully. \n ")

        return redirect('pos:products')
    return render(request, 'pos/user/update_product.html', context)


def delete_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    name = product.name
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product.delete()
        messages.success(request, "Product (" + name + ") Deleted Successfully. \n ")
        return redirect('pos:products')

    return render(request, 'pos/user/delete_product.html', context)


def stock(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }
    return render(request, 'pos/user/stock.html', context)


def add_stock(request, product_id):
    product_list = Product.objects.all()
    product = Product.objects.get(product_id=product_id)
    context = {
        'products': product_list,
        'product': product
    }

    if request.method == "POST":
        product_id = product.product_id
        name = product.name
        quantity = product.quantity + int(request.POST['quantity'])
        unit_price = product.unit_price
        description = product.description

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Stock of (" + name + " " + "Amount: " + request.POST[
            'quantity'] + ") Added Successfully. \n ")
        return redirect('pos:stock')
    return render(request, 'pos/user/add_stock.html', context)


def remove_stock(request, product_id):
    product_list = Product.objects.all()
    product = Product.objects.get(product_id=product_id)
    context = {
        'products': product_list,
        'product': product
    }

    if request.method == "POST":
        product_id = product.product_id
        name = product.name
        quantity = product.quantity - int(request.POST['quantity'])
        unit_price = product.unit_price
        description = product.description

        if quantity < 0:
            messages.error(request, "Stock (" + name + ") is less than the reducing amount")
            return redirect('pos:stock')

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Stock of (" + name + " " + "Amount: " + request.POST[
            'quantity'] + ") Reduced Successfully. \n ")
        return redirect('pos:stock')
    return render(request, 'pos/user/remove_stock.html', context)

pos/views.py
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from pos.models import Product, Sale, SaleItems
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth import logout
from django.contrib import messages
from django.utils import timezone

@login_required
def dashboard(request):
    context = {}
    return render(request, 'pos/user/dashboard.html', context)

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']
        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Login Successful.")
            return redirect('products/1')

        else:
            messages.error(request, "Username or Password is incorrect")

    return render(request, 'pos/auth/login.html')

@login_required
def log_out(request):
    logout(request)
    return render(request, 'pos/auth/logout.html')

@login_required
def account(request):
    uname = request.user.username
    fname = request.user.first_name
    lname = request.user.last_name
    email = request.user.email
    context = {
        'uname': uname,
        'fname': fname,
        'lname': lname,
        'email': email
    }
    return render(request, 'pos/user/account.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        new_password_2 = request.POST.get('new_password_2')

        user = request.user

        print(f"User: {user}")  # Debug: Print current user info
        print(f"Current Password: {current_password}")  # Debug: Print current password entered
        print(f"New Password: {new_password}")  # Debug: Print new password entered
        print(f"New Password Confirmation: {new_password_2}")  # Debug: Print new password confirmation

        # Check if the current password is correct
        if not user.check_password(current_password):
            messages.error(request, 'The current password is incorrect.')
            return redirect('pos:account')

        # Check if the new passwords match
        if new_password != new_password_2:
            messages.error(request, 'The new passwords do not match.')
            return redirect('pos:account')

        # Check password strength and set the new password
        if len(new_password) < 4:
            messages.error(request, 'The new password must be at least 4 characters long.')
            return redirect('pos:account')

        # Set the new password
        user.set_password(new_password)
        user.save()

        if user.check_password(new_password):
            print("Password successfully updated!")  # Debug: Password change confirmation
        else:
            print("Error: Password not updated")  # Debug: Password update failed

        # Keep the user logged in after changing the password
        update_session_auth_hash(request, user)

        messages.success(request, 'Your password has been successfully updated.')
        #return redirect('pos:account')
        return redirect('dashboard')

    return render(request, 'pos/user/account.html')  # Replace with your actual template

def signup(request):
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        username = fname + lname
        username = username.lower()
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!!")
            return redirect('pos:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists!!")
            return redirect('pos:signup')

        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('pos:signup')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.is_active = True

        myuser.save()

        messages.success(request, "Your Account has been created successfully. \n ")

        return redirect('pos:login')

    return render(request, 'pos/auth/signup.html')

@login_required
def products(request, page):
    product_list = Product.objects.all().order_by("product_id")
    paginator = Paginator(product_list, per_page=10)
    page_object = paginator.get_page(page)
    context = {"page_object": page_object}
    return render(request, 'pos/user/products.html', context)

@login_required
def reports(request):
    result_list = None

    if request.method == 'POST':
        start_date_time = request.POST.get('start_date_time')
        end_date_time = request.POST.get('end_date_time')

        if start_date_time and end_date_time:
            # Convert strings to datetime objects
            start_date_time = timezone.datetime.fromisoformat(start_date_time)
            end_date_time = timezone.datetime.fromisoformat(end_date_time)

            # Query the Sale model using date and time ranges
            result_list = Sale.objects.filter(
                date__range=[start_date_time.date(), end_date_time.date()],
                time__range=[start_date_time.time(), end_date_time.time()]
            )
    return render(request, 'pos/user/reports.html', {
        'result_list': result_list,
    })

@login_required
def sales(request, page=1):
    sale_list = Sale.objects.all().order_by("-sale_id")
    paginator = Paginator(sale_list, per_page=12)
    page_object = paginator.get_page(page)
    context = {"page_object": page_object}
    return render(request, "pos/user/sales.html", context)

@login_required
def save_product(request):
    product_list = Product.objects.all()
    page_number = 1
    context = {
        'products': product_list
    }

    if request.method == "POST":
        name = request.POST['name']
        quantity = request.POST['quantity']
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        newproduct = Product.objects.create(name=name, quantity=quantity, unit_price=unit_price,
                                            description=description)

        newproduct.save()
        messages.success(request, "Product (" + name + ") Created Successfully. \n ")

        return redirect('pos:products',page=page_number)
    return render(request, 'pos/user/new_product.html', context)

@login_required
def update_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    page_number = 1
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product_id = product.product_id
        name = request.POST['name']
        quantity = product.quantity
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Product (" + name + ") Updated Successfully. \n ")

        return redirect('pos:products', page=page_number)
    return render(request, 'pos/user/update_product.html', context)

@login_required
def receipt(request, sale_id):
    sale = Sale.objects.get(sale_id=sale_id)
    item_list = SaleItems.objects.filter(sale_id=sale)
    context = {
        'sale': sale,
        'item_list': item_list
    }

    return render(request, 'pos/user/receipt.html', context)

@login_required
def sale_receipt(request, sale_id):
    sale = Sale.objects.get(sale_id=sale_id)
    item_list = SaleItems.objects.filter(sale_id=sale)
    context = {
        'sale': sale,
        'item_list': item_list
    }

    return render(request, 'pos/user/sale_receipt.html', context)

@login_required
def delete_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    name = product.name
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product.delete()
        messages.success(request, "Product (" + name + ") Deleted Successfully. \n ")
        return redirect('pos:products', page=1)

    return render(request, 'pos/user/delete_product.html', context)

@login_required
def stock(request, page):
    product_list = Product.objects.all().order_by("-product_id")
    paginator = Paginator(product_list, per_page=12)
    page_object = paginator.get_page(page)
    context = {"page_object": page_object}
    return render(request, 'pos/user/stock.html', context)

@login_required
def add_stock(request, product_id):
    product_list = Product.objects.all()
    page_number = 1
    product = Product.objects.get(product_id=product_id)
    context = {
        'products': product_list,
        'product': product
    }

    if request.method == "POST":
        product_id = product.product_id
        name = product.name
        quantity = product.quantity + int(request.POST['quantity'])
        unit_price = product.unit_price
        description = product.description

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

templates/pos/user/account.html
{% extends 'pos/user/base.html' %}
{% load static %}

{% block title_block %}
    <title>User Account</title>
{% endblock %}

{% block body_block %}
    <main>
        {% for message in messages %}
        <div class="message">
            {{ message }}
        </div>
        {% endfor %}

        <div class="main3">
            <div class="pill2">
                <div class="pill2_heading_group">
                    <p>BIO DETAILS</p>
                    <!-- <button class="btn-primary" id="bio">UPDATE DETAILS</button> -->
                </div>
                <div class="fieldset">
                    <div class="fieldgroup">
                        <div>
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" value="{{ fname }}" readonly/>
                        </div>
                        <div>
                            <label for="surname">Surname</label>
                            <input id="surname" type="text" value="{{ lname }}" readonly/>
                        </div>
                    </div>
                    
                    <div class="fieldgroup">
                        <div>
                            <label for="username">Username</label>
                            <input id="username" type="text" value="{{ uname }}" readonly/>
                        </div>
                        <div>
                            <label for="email">Email Address</label>
                            <input id="email" type="text" value="{{ email }}" readonly/>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="pill2">
                <div class="pill2_heading_group">
                    <p>USER ACCOUNT DETAILS</p>
                    <button id="update_password_button" class="btn-primary">CHANGE PASSWORD</button>
                </div>
                <div class="fieldset">
                    <div class="fieldgroup">
                        <div>
                            <label for="current_password">Current Password</label>
                            <input id="current_password" value="********" type="password" readonly/>
                        </div>
                    </div>
                    <!-- Added another filedgroup but hidden to align the Flexbox appropriately -->
                    <div class="fieldgroup">
                        <div style="display: none;">
                            <label for="current_password2">Current Password</label>
                            <input id="current_password2" type="password"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- <div id="bio_modal" class="bio_modal">
            <div class="modal-content">
                <p>MODIFY BIO DETAILS</p>
                <form action="{% url 'pos:pos' %}" method="post" id="checkout-form">
                    {% csrf_token %}
                    <input type="hidden" name="checkout" value="true">
                    <div class="fieldWrapper">
                        <label for="first_name">First Name</label>
                        <input class="input" type="text" name="first_name" id="first_name" value="{{fname}}" required>
                    </div>
                    
                    <div class="fieldWrapper">
                        <label for="amountPaid">Surname</label>
                        <input class="input" type="text" name="surname" id="surname" value="{{lname}}" required>
                    </div>
                    
                    <div class="fieldWrapper">
                        <label for="balance">Username</label>
                        <input class="input" type="text" name="username" id="username" value="{{uname}}" readonly>
                    </div>
                    
                    <div class="fieldWrapper">
                        <label for="balance">Email Address</label>
                        <input class="input" type="text" name="balance" id="balance" value="{{email}}" readonly>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button type="button" id="cancel-checkout" class="btn-secondary"> CANCEL </button>
                    </div>
                </form>
            </div>
        </div> -->

        <div id="update_password_modal" class="modal">
            <div class="modal-content">
                <p>MODIFY ACCOUNT DETAILS</p>
                <form action="{% url 'pos:change_password' %}" method="post" id="checkout-form">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="current_password">Current Password</label>
                        <input class="input" type="password" name="current_password" required>
                    </div>
                    
                    <div class="fieldWrapper">
                        <label for="new_password">New Password</label>
                        <input class="input" type="password" name="new_password" id="new_password" required>
                    </div>
                    
                    <div class="fieldWrapper">
                        <label for="new_password_2">Confirm New Password</label>
                        <input class="input" type="password" name="new_password_2" id="new_password_2" required>
                    </div>
                    
                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button type="button" id="cancel" class="btn-secondary"> CANCEL </button>
                    </div>
                </form>
            </div>
        </div>
    </main>

    {% block script_block %}
        <script type="text/javascript">
            const bio = document.getElementById("bio");
            const account = document.getElementById("account");
            // const bio_modal = document.getElementById("bio_modal");
            const update_password_modal = document.getElementById("update_password_modal");
            const update_password_button = document.getElementById("update_password_button");
            const cancel_button = document.getElementById("cancel");

            update_password_button.addEventListener('click', function() {
                update_password_modal.style.display = "block";
            });

            cancel_button.addEventListener('click', function() {
                update_password_modal.style.display = "none";
            });

            // window.onload = function () {
            //     modal.style.display = "block";
            // }

            cancel.onclick = function () {
                modal.style.display = "none";
            }

            // window.onclick = function(event) {
            //     if (event.target === modal) {
            //         location.href = "/pos/products/1";
            //     }
            // }

            product.onclick = function () {
                location.href = "/pos/products/1";
            };
        </script>
    {% endblock %}
{% endblock %}

templates/pos/user/delete_product.html
{% extends 'pos/user/products.html' %}
{% load static %}
{% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content" style="width: 25%;margin-top: 10%">
                <p>DELETE PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label>ARE YOU SURE?</label>
                        <label>DELETE {{ product.name }}</label>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="YES"/>
                        <a class="btn-secondary" style="width:54px;justify-content:center;text-decoration: none" href="{% url 'pos:products' 1 %}">NO</a>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");

        window.onload = function () {
            modal.style.display = "block";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}

templates/pos/user/products.html
{% extends 'pos/user/base.html' %}
{% load static %}

{% block title_block %}
    <title>Products</title>
{% endblock %}

{% block body_block %}
    <main>
        {% for message in messages %}
            <div class="message">
                {{ message }}
            </div>
        {% endfor %}

        <button id="new" class="btn-primary">
            <img alt="home" src="{% static 'images/plus.svg' %}"/>
            ADD NEW
        </button>

        <table class="product">
            <thead>
                <tr>
                    <th>PRODUCT ID</th>
                    <th>PRODUCT NAME</th>
                    <th>UNIT PRICE</th>
                    <th>QUANTITY</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                {% for product in page_object %}
                <tr>
                    <td>{{ product.product_id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.unit_price }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        <a class="no-underline" href="{% url 'pos:update_product' product.product_id %}">
                            <img id="edit" alt="edit" class="icon" src="{% static 'images/edit.svg' %}"/>
                        </a>
                        <a class="no-underline" href="{% url 'pos:delete_product' product.product_id %}">
                            <img alt="delete" src="{% static 'images/delete.svg' %}"/>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot></tfoot>
                <tr>
                    <td>Page {{ page_object.number }} of {{ page_object.paginator.num_pages }}</td>
                    <td colspan="4">
                        <div class="pagination-cell">
                            <a class="pagination-ends" href="{% url 'pos:products' 1 %}">&laquo;</a>
                            {% for num in page_object.paginator.page_range %}
                                {% if page_object.number == num %}
                                    <span class="pagination-active">{{ num }}</span>
                                {% else %}
                                    <a class="pagination" href="{% url 'pos:products' num %}">{{ num }}</a>
                                {% endif %}
                            {% endfor %}
                            <a class="pagination-ends" href="{% url 'pos:products' page_object.paginator.num_pages|default:1 %}">&raquo;</a>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>

        {% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>ADD NEW PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="price">Price in Kshs</label>
                        <input class="input" type="number" name="price" id="price" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="description">Description</label>
                        <textarea class="input" name="description" id="description"></textarea>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% endblock %}
    </main>

    {% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new");
        let cancel = document.getElementById("cancel");
        let edit = document.getElementById("edit");

        btn_new.onclick = function () {
            location.href = "/pos/save_product";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        }
    </script>
    {% endblock %}

{% endblock %}