app/jaythree/urls.py
from django import views
from pos import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pos/', include('pos.urls')),
    path('', views.dashboard, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/pos/urls.py
from django.urls import path
from . import views

app_name = 'pos'

urlpatterns = [
    path('stock', views.stock, name='stock'),
    path('products', views.products, name='products'),
    path('save_product', views.save_product, name='save_product'),
    path('delete_product/<str:product_id>', views.delete_product, name='delete_product'),
    path('update_product/<str:product_id>', views.update_product, name='update_product'),
    path('add_stock/<str:product_id>', views.add_stock, name='add_stock'),
    path('remove_stock/<str:product_id>', views.remove_stock, name='remove_stock'),
]

app/pos/models.py
from django.db import models
from django.utils import timezone


class Product(models.Model):
    product_id = models.SmallAutoField(primary_key=True)
    name = models.CharField(max_length=200)
    quantity = models.IntegerField(default=0)
    unit_price = models.IntegerField(default=0)
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Sale(models.Model):
    sale_id = models.SmallAutoField(primary_key=True)
    code = models.CharField(max_length=200, blank=True)
    date = models.DateField(default=timezone.now)
    time = models.TimeField()
    total = models.IntegerField(default=0)
    tendered_amount = models.IntegerField(default=0)
    customer_name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.code


class SaleItems(models.Model):
    sale_id = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    total = models.IntegerField(default=0)

app/pos/views.py
from django.shortcuts import redirect, render
from django.shortcuts import render, redirect
from pos.models import Product
from django.contrib import messages

def dashboard(request):
    context = {}
    return render(request, 'pos/user/dashboard.html', context)


def products(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }
    return render(request, 'pos/user/products.html', context)


def save_product(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }

    if request.method == "POST":
        name = request.POST['name']
        quantity = request.POST['quantity']
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        newproduct = Product.objects.create(name=name, quantity=quantity, unit_price=unit_price,
                                            description=description)

        newproduct.save()
        messages.success(request, "Product (" + name + ") Created Successfully. \n ")

        return redirect('pos:products')
    return render(request, 'pos/user/new_product.html', context)


def update_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product_id = product.product_id
        name = request.POST['name']
        quantity = product.quantity
        unit_price = request.POST['unit_price']
        description = request.POST['description']

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Product (" + name + ") Updated Successfully. \n ")

        return redirect('pos:products')
    return render(request, 'pos/user/update_product.html', context)


def delete_product(request, product_id):
    product = Product.objects.get(product_id=product_id)
    name = product.name
    product_list = Product.objects.all()
    context = {
        'product': product,
        'products': product_list
    }

    if request.method == "POST":
        product.delete()
        messages.success(request, "Product (" + name + ") Deleted Successfully. \n ")
        return redirect('pos:products')

    return render(request, 'pos/user/delete_product.html', context)


def stock(request):
    product_list = Product.objects.all()
    context = {
        'products': product_list
    }
    return render(request, 'pos/user/stock.html', context)


def add_stock(request, product_id):
    product_list = Product.objects.all()
    product = Product.objects.get(product_id=product_id)
    context = {
        'products': product_list,
        'product': product
    }

    if request.method == "POST":
        product_id = product.product_id
        name = product.name
        quantity = product.quantity + int(request.POST['quantity'])
        unit_price = product.unit_price
        description = product.description

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Stock of (" + name + " " + "Amount: " + request.POST[
            'quantity'] + ") Added Successfully. \n ")
        return redirect('pos:stock')
    return render(request, 'pos/user/add_stock.html', context)


def remove_stock(request, product_id):
    product_list = Product.objects.all()
    product = Product.objects.get(product_id=product_id)
    context = {
        'products': product_list,
        'product': product
    }

    if request.method == "POST":
        product_id = product.product_id
        name = product.name
        quantity = product.quantity - int(request.POST['quantity'])
        unit_price = product.unit_price
        description = product.description

        if quantity < 0:
            messages.error(request, "Stock (" + name + ") is less than the reducing amount")
            return redirect('pos:stock')

        updated_product = Product(product_id=product_id, name=name, quantity=quantity, unit_price=unit_price,
                                  description=description)

        updated_product.save()

        messages.success(request, "Stock of (" + name + " " + "Amount: " + request.POST[
            'quantity'] + ") Reduced Successfully. \n ")
        return redirect('pos:stock')
    return render(request, 'pos/user/remove_stock.html', context)

app/templates/pos/user/add_stock.html
{% extends 'pos/user/stock.html' %}
{% load static %}
{% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>ADD STOCK</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" value="{{product.name}}" readonly>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" value="{{product.quantity}}" readonly>
                    </div>

                    <div class="fieldWrapper">
                        <label for="amount_added">Amount Added</label>
                        <input class="input" type="number" name="quantity" id="amount_added" min="0" required>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new");
        let cancel = document.getElementById("cancel");

        window.onload = function () {
            modal.style.display = "block";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}

app/templates/pos/user/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/styles/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400&family=Open+Sans:wght@300;400;500&display=swap" rel="stylesheet">
    {% block title_block %}
    {% endblock %}
</head>
<body>
    <nav class="sidebar">
        <button id="dashboard">
            <img alt="home" class="nav-logo" src="{% static 'images/home.svg' %}"/>
            Dashboard
        </button>
        <button id="product">
            <img alt="home" class="nav-logo" src="{% static 'images/box.svg' %}"/>
            Product
        </button>
        <button>
            <img alt="home" class="nav-logo" src="{% static 'images/pos.svg' %}"/>
            POS
        </button>
        <button id="stock">
            <img alt="home" class="nav-logo" src="{% static 'images/stock.svg' %}"/>
            Stock
        </button>
        <button>
            <img alt="home" class="nav-logo" src="{% static 'images/sales.svg' %}"/>
            Sales
        </button>
        <button>
            <img alt="home" class="nav-logo" src="{% static 'images/report.svg' %}"/>
            Daily Reports
        </button>
        <button>
            <img alt="home" class="nav-logo" src="{% static 'images/report.svg' %}"/>
            Weekly Reports
        </button>
        <button>
            <img alt="home" class="nav-logo" src="{% static 'images/report.svg' %}"/>
            Monthly Reports
        </button>
    </nav>

    <div class="parent">
        <nav class="topbar">
            <p id="date"></p>
            <p>Greg Atemi</p>
        </nav>

    {% block body_block %}

    {% endblock %}
    </div>
    {% block footer_block %}
    {% endblock %}
</body>

<script type="text/javascript">

    let dashboard = document.getElementById("dashboard");
    let product = document.getElementById("product");
    let stock = document.getElementById("stock");

    dashboard.onclick = function () {
        location.href = "";
    };

    product.onclick = function () {
        location.href = "/pos/products";
    };

    stock.onclick = function () {
        location.href = "/pos/stock";
    };
</script>

</html>

app/templates/pos/user/dashboard.html
{% extends 'pos/user/base.html' %}
{% load static %}

{% block title_block %}
    <title>Dashboard</title>
{% endblock %}

{% block body_block %}
    <div class="main2">
        <div class="pill">
            <span class="big">30</span>
            <span>Products</span>
        </div>
        <div class="pill">
            <span class="big">30</span>
            <span>Products</span>
        </div>
        <div class="pill">
            <span class="big">30</span>
            <span>Products</span>
        </div>
    </div>
{% endblock %}

app/templates/pos/user/delete_product.html
{% extends 'pos/user/products.html' %}
{% load static %}
{% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content" style="width: 25%;margin-top: 10%">
                <p>DELETE PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label>ARE YOU SURE?</label>
                        <label>DELETE {{ product.name }}</label>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="YES"/>
                        <a class="btn-secondary" style="width:54px;justify-content:center;text-decoration: none" href="{% url 'pos:products' %}">NO</a>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");

        window.onload = function () {
            modal.style.display = "block";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}

app/templates/pos/user/new_product.html
{% extends 'pos/user/products.html' %}
{% load static %}
{% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>ADD NEW PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="unit_price">Price in Kshs</label>
                        <input class="input" type="number" name="unit_price" id="unit_price" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="description">Description</label>
                        <textarea class="input" name="description" id="description"></textarea>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new");
        let cancel = document.getElementById("cancel");

        window.onload = function () {
            modal.style.display = "block";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}

app/templates/pos/user/products.html
{% extends 'pos/user/base.html' %}
{% load static %}

{% block title_block %}
    <title>Products</title>
{% endblock %}

{% block body_block %}
    <main>
        {% for message in messages %}
            <div class="message">
                {{ message }}
            </div>
        {% endfor %}

        <button id="new" class="btn-primary">
            <img alt="home" src="{% static 'images/plus.svg' %}"/>
            ADD NEW
        </button>

        <table class="product">
            <thead>
                <tr>
                    <th>PRODUCT ID</th>
                    <th>PRODUCT NAME</th>
                    <th>UNIT PRICE</th>
                    <th>QUANTITY</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.product_id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.unit_price }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        <a href="{% url 'pos:update_product' product.product_id %}">
                            <img id="edit"  alt="edit" class="icon" src="{% static 'images/edit.svg' %}"/>
                        </a>
                        <a href="{% url 'pos:delete_product' product.product_id %}">
                            <img alt="delete" src="{% static 'images/delete.svg' %}"/>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>ADD NEW PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="price">Price in Kshs</label>
                        <input class="input" type="number" name="price" id="price" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="description">Description</label>
                        <textarea class="input" name="description" id="description"></textarea>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% endblock %}
    </main>

    {% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new");
        let cancel = document.getElementById("cancel");
        let edit = document.getElementById("edit");

        btn_new.onclick = function () {
            location.href = "/pos/save_product";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        }
    </script>
    {% endblock %}

{% endblock %}

app/templates/pos/user/remove_stock.html
{% extends 'pos/user/stock.html' %}
{% load static %}
{% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>REMOVE STOCK</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" value="{{product.name}}" readonly>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" value="{{product.quantity}}" readonly>
                    </div>

                    <div class="fieldWrapper">
                        <label for="amount_reduced">Amount Reduced</label>
                        <input class="input" type="number" name="quantity" id="amount_reduced" min="0" required>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new");
        let cancel = document.getElementById("cancel");

        window.onload = function () {
            modal.style.display = "block";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}

app/templates/pos/user/stock.html
{% extends 'pos/user/base.html' %}
{% load static %}

{% block title_block %}
    <title>Stock</title>
{% endblock %}

{% block body_block %}
    <main>
        {% for message in messages %}
            <div class="message">
                {{ message }}
            </div>
        {% endfor %}

        <button id="new_product" class="btn-primary">
            <img alt="home" src="{% static 'images/plus.svg' %}"/>
            ADD NEW PRODUCT
        </button>

        <table class="product">
            <thead>
                <tr>
                    <th>PRODUCT ID</th>
                    <th>PRODUCT NAME</th>
                    <th>QUANTITY</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.product_id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.quantity }}</td>
                    <td class="button-cell">
                        <a class="btn-primary2" href="{% url 'pos:add_stock' product.product_id %}">
                            ADD
                        </a>
                        <a class="btn-secondary2" href="{% url 'pos:remove_stock' product.product_id %}">
                            REMOVE
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% block content_block %}
        <div id="modal" class="modal">
            <div class="modal-content">
                <p>ADD NEW PRODUCT</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="name">Name</label>
                        <input class="input" type="text" name="name" id="name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="quantity">Quantity</label>
                        <input class="input" type="number" name="quantity" id="quantity" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="price">Price in Kshs</label>
                        <input class="input" type="number" name="price" id="price" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="description">Description</label>
                        <textarea class="input" name="description" id="description"></textarea>
                    </div>

                    <div class="button-group">
                        <input class="btn-primary" type="submit" value="SAVE"/>
                        <button id="cancel" class="btn-secondary">
                            CANCEL
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% endblock %}
    </main>

    {% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");
        let btn_new = document.getElementById("new_product");
        let cancel = document.getElementById("cancel");
        let edit = document.getElementById("edit");

        btn_new.onclick = function () {
            location.href = "/pos/products";
        }

        cancel.onclick = function () {
            modal.style.display = "none";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        }
    </script>
    {% endblock %}

{% endblock %}

app/templates/pos/user/update_product.html
{% extends 'pos/user/products.html' %}
{% load static %}
{% block content_block %}
    <div id="modal" class="modal">
        <div class="modal-content">
            <p>UPDATE PRODUCT</p>
            <form action="" method="post">
                {% csrf_token %}
                <div class="fieldWrapper">
                    <label for="name">Name</label>
                    <input class="input" type="text" name="name" id="name" value="{{product.name}}" required>
                </div>

                <div class="fieldWrapper">
                    <label for="quantity">Quantity</label>
                    <input class="input" type="number" name="quantity" id="quantity" value="{{product.quantity}}" disabled>
                </div>

                <div class="fieldWrapper">
                    <label for="unit_price">Price in Kshs</label>
                    <input class="input" type="number" name="unit_price" id="unit_price" value="{{product.unit_price}}" required>
                </div>

                <div class="fieldWrapper">
                    <label for="description">Description</label>
                    <textarea class="input" name="description" id="description"></textarea>
                </div>

                <div class="button-group">
                    <input class="btn-primary" type="submit" value="SAVE"/>
                    <a class="btn-secondary" style="width:54px;justify-content:center;text-decoration: none" href="{% url 'pos:products' %}">CANCEL</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block script_block %}
    <script type="text/javascript">
        let modal = document.getElementById("modal");

        window.onload = function () {
            modal.style.display = "block";
        }

        window.onclick = function(event) {
            if (event.target === modal) {
                location.href = "/pos/products";
            }
        }

        product.onclick = function () {
            location.href = "/pos/products";
        };
    </script>
{% endblock %}